export const dummyData =
  [{
    userName: '해시태그닷',
    uploadTime: '1분 전',
    title: '목적없이 떠나는 드라이브 VLOG',
    thumbnail: 'https://i.ibb.co/hYjK44F/anise-aroma-art-bazaar-277253.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#V #목적없이떠나는여행 #꼬막비빔밥',
    heart: 33,
  },
  {
    userName: '비디오닷',
    uploadTime: '10분 전',
    title: '목적없이 떠나는 여행 VLOG',
    thumbnail: 'https://i.ibb.co/JtS24qP/food-inside-bowl-1854037.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#서울 #드라이브 #남자친구',
    heart: 28,
  },
  {
    userName: '쿠크닷스',
    uploadTime: '1일 전',
    title: '목적없이 떠나버려 VLOG',
    thumbnail: 'https://i.ibb.co/JxykVBt/flat-lay-photography-of-vegetable-salad-on-plate-1640777.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#요리 #오늘은내가짜파게티요리사 #꿀맛',
    heart: 22,
  },
  {
    userName: '쿠크닷스',
    uploadTime: '2일 전',
    title: '목적없이 떠나버려 VLOG',
    thumbnail: 'https://i.ibb.co/JxykVBt/flat-lay-photography-of-vegetable-salad-on-plate-1640777.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#요리 #오늘은내가짜파게티요리사 #꿀맛',
    heart: 22,
  },
  {
    userName: '쿠크닷스',
    uploadTime: '13일 전',
    title: '목적없이 떠나버려 VLOG',
    thumbnail: 'https://i.ibb.co/JxykVBt/flat-lay-photography-of-vegetable-salad-on-plate-1640777.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#요리 #오늘은내가짜파게티요리사 #꿀맛',
    heart: 22,
  },
  {
    userName: '쿠크닷스',
    uploadTime: '14일 전',
    title: '목적없이 떠나버려 VLOG',
    thumbnail: 'https://i.ibb.co/JxykVBt/flat-lay-photography-of-vegetable-salad-on-plate-1640777.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#요리 #오늘은내가짜파게티요리사 #꿀맛',
    heart: 22,
  },
  {
    userName: '쿠크닷스',
    uploadTime: '15일 전',
    title: '목적없이 떠나버려 VLOG',
    thumbnail: 'https://i.ibb.co/JxykVBt/flat-lay-photography-of-vegetable-salad-on-plate-1640777.jpg',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: '#요리 #오늘은내가짜파게티요리사 #꿀맛',
    heart: 22,
  }]